// THIS FILE IS AUTO-GENERATED BY `scripts/generate-types.ts`. DO NOT EDIT.

import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import type { users } from '~/db/schema/users';
import type { forms } from '~/db/schema/forms';
import type { sections } from '~/db/schema/sections';
import type { formUsers } from '~/db/schema/formUsers';

// ------------- SELECT TYPES ------------- //
export type User = InferInsertModel<typeof users>;
export type Form = InferInsertModel<typeof forms>;
export type Section = InferInsertModel<typeof sections>;
export type FormUser = InferInsertModel<typeof formUsers>;

// ------------- INSERT TYPES ------------- //
export type NewUser = InferSelectModel<typeof users>;
export type NewForm = InferSelectModel<typeof forms>;
export type NewSection = InferSelectModel<typeof sections>;
export type NewFormUser = InferSelectModel<typeof formUsers>;
