// scripts/generate-types.ts

import ts from 'typescript';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// --- CONFIGURATION ---

// Convert ESM URL to file path
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Adjust this based on how deep your script is nested
const projectRoot = path.resolve(__dirname, '..');

const schemaFilePath = path.resolve(projectRoot, './drizzle/schema.ts');
const outputFilePath = path.resolve(projectRoot, 'src/db/types.ts');// --- END CONFIGURATION ---

/**
 * Converts a plural table name (like 'users') to a singular, capitalized type name (like 'User').
 */
function getTypeName(tableName: string): string {
    let singularName = tableName;
    if (singularName.endsWith('s')) {
        singularName = singularName.slice(0, -1);
    }
    return singularName.charAt(0).toUpperCase() + singularName.slice(1);
}

function generateTypes() {
    console.log(`🔍 Reading schema from: ${schemaFilePath}`);

    const program = ts.createProgram([schemaFilePath], { allowJs: true });
    const sourceFile = program.getSourceFile(schemaFilePath);

    if (!sourceFile) {
        throw new Error('Could not find the schema source file.');
    }

    const exportedTableNames: string[] = [];

    // Walk the AST to find exported pgTable variables
    ts.forEachChild(sourceFile, (node) => {
        if (
            ts.isVariableStatement(node) &&
            node.modifiers?.some(mod => mod.kind === ts.SyntaxKind.ExportKeyword)
        ) {
            node.declarationList.declarations.forEach(declaration => {
                if (
                    ts.isIdentifier(declaration.name) &&
                    declaration.initializer &&
                    ts.isCallExpression(declaration.initializer) &&
                    ts.isIdentifier(declaration.initializer.expression) &&
                    declaration.initializer.expression.text === 'pgTable'
                ) {
                    const varName = declaration.name.text;
                    exportedTableNames.push(varName);
                }
            });
        }
    });
    ;

    if (exportedTableNames.length === 0) {
        console.warn('⚠️ No exported pgTable variables found in schema file.');
        return;
    }

    console.log(`✅ Found tables: ${exportedTableNames.join(', ')}`);

    // --- GENERATE FILE CONTENT ---
    const imports = exportedTableNames.map(name => `import type { ${name} } from '~/db/schema/${name}';`).join('\n');

    const selectTypes = exportedTableNames.map(name => {
        const typeName = getTypeName(name);
        return `export type ${typeName} = InferInsertModel<typeof ${name}>;`;
    }).join('\n');

    const insertTypes = exportedTableNames.map(name => {
        const typeName = getTypeName(name);
        return `export type New${typeName} = InferSelectModel<typeof ${name}>;`;
    }).join('\n');

    const fileContent = `// THIS FILE IS AUTO-GENERATED BY \`scripts/generate-types.ts\`. DO NOT EDIT.

import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
${imports}

// ------------- SELECT TYPES ------------- //
${selectTypes}

// ------------- INSERT TYPES ------------- //
${insertTypes}
`;
    // --- END GENERATE FILE CONTENT ---

    fs.writeFileSync(outputFilePath, fileContent);
    console.log(`🎉 Successfully generated types at: ${outputFilePath}`);
}

try {
    generateTypes();
} catch (error) {
    console.error('❌ An error occurred during type generation:', error);
    process.exit(1);
}
